version: '3.8'

services:
  cisco-meraki-web:
    build: .
    container_name: cisco-meraki-web-app
    ports:
      - "5000:5000"
      - "5001-5010:5001-5010"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - WEB_MODE=true
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
      - ./templates:/app/templates
      - ./static:/app/static
      - ./visualizations:/app/visualizations
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  config:
    driver: local
  logs:
    driver: local
  data:
    driver: local